# Name: Insight Platform Landing Zone Rules
# Description: A collection of rules and suppression group rules that support the use of the `/src/` Bicep files that have been purposefully created to be more modular in design than the Microsoft Cloud Adoption Framework (CAF) and Microsoft Well Architected Review (WAR) standards support for the Platform Landing Zone. These rules should be updated or reviewed whenever changes are made to these files.
---
# Synopsis: Suppression for Azure.NSG.LateralTraversal for Network Security Groups
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: Insight.SuppressNSG.HubNetworking
  description: 'AZR-000139: Consider configuring NSGs rules to block common outbound management traffic from non-management hosts.'
spec:
  if:
    allOf:
      - source: 'Template'
        endsWith:
          - 'hubNetworking.bicep'
          - 'platformIdentity.bicepparam'
          - 'platformManagement.bicepparam'
  rule:
    - Azure.NSG.LateralTraversal

---
# Synopsis: Ignore automation account audit diagnostic logs are enabled on logging.bicep
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: Insight.DiagLogForAutomation.Automation
spec:
  rule:
    - Azure.Automation.AuditLogs
    - Azure.Automation.PlatformLogs
  if:
    allOf:
      - source: 'Template'
        endsWith:
          - 'logging.bicep'

---
# Synopsis: Suppression for Azure.PublicIP.AvailabilityZone
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressPublicIPAvailabilityZone
  description: 'AZR-000157: Consider using zone-redundant Public IP addresses deployed with Standard SKU.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/publicIPAddresses'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.PublicIP.AvailabilityZone

---
# Synopsis: Suppression for Azure.NSG.LateralTraversal for Public IP
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressNSGLateralTraversal_PublicIP
  description: 'AZR-000139: Consider configuring NSGs rules to block common outbound management traffic from non-management hosts.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/publicIPAddresses'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.NSG.LateralTraversal

---
# Synopsis: Suppression for Azure.Automation.PlatformLogs
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressAutomationPlatformLogs
  description: 'AZR-000089: Consider configuring diagnostic settings to capture platform logs from Automation accounts.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Automation/automationAccounts'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Automation.PlatformLogs

---
# Synopsis: Suppression for Azure.Resource.UseTags for network security groups
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForNSG
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard. Also consider using Azure Policy to enforce mandatory tags.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/networkSecurityGroups'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for virtual networks
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForVNet
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/virtualNetworks'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for bastion hosts
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForBastionHosts
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/bastionHosts'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for virtual network gateways
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForVNetGateways
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/virtualNetworkGateways'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for firewall policies
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForFirewallPolicies
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/firewallPolicies'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for publicIPAddresses
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForPublicIP
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/publicIPAddresses'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for AzureFirewalls
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForAzureFirewalls
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/azureFirewalls'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for RouteTables
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForRouteTables
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/routeTables'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for LocalNetworkGateways
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForLocalNetworkGateways
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/localNetworkGateways'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for Network Connections
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForNetworkConnections
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/connections'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for Network Watchers
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForNetworkWatchers
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/networkWatchers'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for Resource Groups
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForResourceGroups
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Resources/resourceGroups'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Deployment.AdminUsername
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressDeploymentAdminUsername
  description: 'Ref AZR-000284: Sensitive properties should be passed as parameters. Avoid using deterministic values for sensitive properties.'
spec:
  if:
    allOf:
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Deployment.AdminUsername

---
# Synopsis: Suppression for Azure.Resource.UseTags for Deployments
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForDeployments
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Resource.UseTags for WAF-Aligned Tests
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForWAFAligned
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Resources/resourceGroups'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Resource.UseTags

---
# Synopsis: Suppression for Azure.Deployment.AdminUsername for WAF-Aligned Tests
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressDeploymentAdminUsernameWAFAligned
  description: 'Ref AZR-000284: Sensitive properties should be passed as parameters. Avoid using deterministic values for sensitive properties.'
spec:
  if:
    allOf:
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Deployment.AdminUsername

---
# Synopsis: Suppression for Azure.Policy.AssignmentAssignedBy for Azure Policy
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressPolicyAssignmentAssignedBy
  description: 'Azure Policy AssignmentAssignedBy not used in the platform deployment.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Authorization/policyAssignments'
      - source: 'Template'
        withinPath:
          - 'src/modules'
  rule:
    - Azure.Policy.AssignmentAssignedBy

---
# Synopsis: Suppression for Azure.VM.AMA for Virtual Machines
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressAzureVmAmaForVirtualMachines
  description: 'Deployment of Azure Monitor Agent (AMA) is managed through Azure Policy.'
spec:
  rule:
    - Azure.VM.AMA
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Compute/virtualMachines'

---
# Synopsis: Suppression for Azure.VM.MaintenanceConfig for Virtual Machines
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressAzureVmMaintenanceConfigForVirtualMachines
  description: 'The maintenance configuration is managed through either Azure Update Manager or other tools.'
spec:
  rule:
    - Azure.VM.MaintenanceConfig
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Compute/virtualMachines'

---
# Synopsis: Suppression for Azure.Resource.UseTags for Security Insights
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceUseTagsForSecurityInsights
  description: 'Ref AZR-000166: Consider tagging resources using a standard convention. Identify mandatory and optional tags then tag all resources and resource groups using this standard. Also consider using Azure Policy to enforce mandatory tags'
spec:
  rule:
    - Azure.Resource.UseTags
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.SecurityInsights/onboardingStates'
---
# Synopsis: Suppression for Azure.VNET.SubnetNaming for Platform Subnets
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceAzureVNETSubnetNaming
  description: 'Virtual Network subnets names will be derived based on the CAF Naming standards.'
spec:
  rule:
    - Azure.VNET.SubnetNaming
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/virtualNetworks'
      - field: properties.subnets[*]
        anyOf:
          - field: name
            hasValue: true

---
# Synopsis: Suppression for Azure.KeyVault.Firewall for Application Gateway
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceAzureKeyVaultFirewall
  description: 'Azure Key Vault network policies will be imposed through Azure Policy and will be denied by default.'
spec:
  rule:
    - Azure.KeyVault.Firewall
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.KeyVault/vaults'

---
# Synopsis: Suppression for Azure.VM.DiskCaching for Virtual Machines
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressAzureVmDiskCachingForVirtualMachines
  description: 'Disk caching is configured correctly at the workload.'
spec:
  rule:
    - Azure.VM.DiskCaching
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Compute/virtualMachines'

---
# Synopsis: Suppression for Azure.VNET.SingleDNS for Platform Virtual Networks
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceAzureVNETSingleDNS
  description: 'Platform Virtual Networks will be pointed to the Azure Firewall Private IP which addresses redundancy'
spec:
  rule:
    - Azure.VNET.SingleDNS
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/virtualNetworks'
      - field: properties.dhcpOptions
        anyOf:
          - field: dnsServers
            hasValue: true

---
# Synopsis: Suppression for Azure.VNET.SubnetNaming for Azure Virtual Networks
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceAzureKeyVaultRBAC
  description: 'Azure Key Vault RBAC permission model will not be used by Azure Firewall to manage access to the Key Vault due to Firewall limitation.'
spec:
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.KeyVault/vaults'
      - field: tags.Purpose
        equals: 'TLS Certificate reference for Azure Firewall Policy'
  rule:
    - Azure.KeyVault.RBAC

---
# Synopsis: Suppression for Azure.VNET.PrivateSubnet for Platform Virtual Networks
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressResourceAzurePrivateSubnet
  description: 'Virtual Networks will be allow subnet outbound access by default as they are controlled by the centralised Azure Firewall.'
spec:
  rule:
    - Azure.VNET.PrivateSubnet
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/virtualNetworks'

---
# Synopsis: Suppression for Azure.Log.Replication for Platform Management Log Analytics
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressAzureLogReplicationForPlatformManagement
  description: 'Platform Management Log Analytics workspace is not replicated to a secondary region as part of the platform design.'
spec:
  rule:
    - Azure.Log.Replication
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.OperationalInsights/workspaces'
      - source: 'Template'
        withinPath:
          - 'src/modules/platformManagement.bicep'

---
# Synopsis: Suppression for Azure.Log.Replication for Platform Management Log Analytics - Parameter
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressAzureLogReplicationForPlatformManagementParameter
  description: 'Platform Management Log Analytics workspace is not replicated to a secondary region as part of the platform design.'
spec:
  rule:
    - Azure.Log.Replication
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.OperationalInsights/workspaces'
      - source: 'Parameter'
        withinPath:
          - 'src/configuration/platform'

---
# Synopsis: Supression for Azure.VNG.MaintenanceConfig for Platform Virtual Network Gateways
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressAzureVirtualNetworkGatewayMaintenanceConfig
  description: 'Platform Management does not contain Virtual Network Gateway Maintenance Configurations as part of the platform design.'
spec:
  rule:
    - Azure.VNG.MaintenanceConfig
  if:
    allOf:
      - type: '.'
        in:
          - 'Microsoft.Network/virtualNetworkGateways'
