---
name: deploy-role

on:
  workflow_call:
    inputs:
      artifactName:
        required: true
        type: string
        default: artifact
      environmentName:
        required: true
        type: string
      location:
        required: true
        type: string
      managementGroupId:
        type: string
      configKey_roleDefinitions:
        required: true
        type: string
      configKey_roleAssignments:
        required: true
        type: string
      moduleName:
        required: true
        type: string
      whatIf:
        required: true
        type: boolean
        default: false
      enableRoleAssignments:
        default: true
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  rbac:
    name: deploy
    environment: ${{ inputs.environmentName }}
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      # Download Artifact
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifactName }}

      - name: Read Platform Variables
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: read-yaml
        with:
          config: ${{ github.workspace }}/.github/platform-variables.yml

      - name: Set Platform Variables
        run: |
          echo "templateFileKey_roleDefintions=${{ inputs.configKey_roleDefinitions }}.templateFile" >> $GITHUB_ENV
          echo "templateParameterFileKey_roleDefinitions=${{ inputs.configKey_roleDefinitions }}.templateParameterFile" >> $GITHUB_ENV
          echo "templateFileKey_roleAssignments=${{ inputs.configKey_roleAssignments }}.templateFile" >> $GITHUB_ENV
          echo "templateParameterFileKey_roleAssignments=${{ inputs.configKey_roleAssignments }}.templateParameterFile" >> $GITHUB_ENV

      # Azure Login
      - name: Az Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      # Role Definitions

      - name: Deploy Role Definitions
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |

            managementGroupId="${{ inputs.managementGroupId }}"
            location="${{ inputs.location }}"
            templateFile="${{ steps.read-yaml.outputs[env.templateFileKey_roleDefintions] }}"
            templateParameterFile="${{ steps.read-yaml.outputs[env.templateParameterFileKey_roleDefinitions] }}"
            DEPLOYMENTJOBID="alz-role-defintions-${{ github.run_number }}"

            if [ ${{ inputs.whatIf }} == 'true' ]; then
              az deployment mg what-if -n $DEPLOYMENTJOBID -m $managementGroupId -l $location -f $templateFile -p $templateParameterFile -x Ignore NoChange Unsupported -r FullResourcePayloads
              az deployment mg create -n $DEPLOYMENTJOBID -m $managementGroupId -l $location -f $templateFile -p $templateParameterFile
            else
              az deployment mg create -n $DEPLOYMENTJOBID -m $managementGroupId -l $location -f $templateFile -p $templateParameterFile
            fi

      # Role Assignments

      - name: Deploy Role Assignments
        if: ${{ inputs.enableRoleAssignments }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |

            managementGroupId="${{ inputs.managementGroupId }}"
            location="${{ inputs.location }}"
            templateFile="${{ steps.read-yaml.outputs[env.templateFileKey_roleAssignments] }}"
            templateParameterFile="${{ steps.read-yaml.outputs[env.templateParameterFileKey_roleAssignments] }}"
            DEPLOYMENTJOBID="alz-role-${{ github.run_number }}"

            if [ ${{ inputs.whatIf }} == 'true' ]; then
              az deployment mg what-if -n $DEPLOYMENTJOBID -m $managementGroupId -l $location -f $templateFile -p $templateParameterFile -x Ignore NoChange Unsupported -r FullResourcePayloads
              az deployment mg create -n $DEPLOYMENTJOBID -m $managementGroupId -l $location -f $templateFile -p $templateParameterFile
            else
              az deployment mg create -n $DEPLOYMENTJOBID -m $managementGroupId -l $location -f $templateFile -p $templateParameterFile
            fi

      # Log out of Azure
      - name: Az Logout
        run: az logout
