name: PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  PSRULE_DIRECTORY: ./
  INFRA_WORKING_DIRECTORY: ./
  currencyCode: 'AUD'
  location: 'australiaeast'

jobs:
  linting:
    name: Lint Testing
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

        # Linting
      - name: Lint Testing
        uses: super-linter/super-linter@v8
        env:
          DEFAULT_BRANCH: 'main'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_POWERSHELL: true
          VALIDATE_YAML: true
          FIX_MARKDOWN: true
          FILTER_REGEX_EXCLUDE: .*/(src/modules/[^/]+|docs/wiki/(Bicep|PS-Rule|Scripts|Pricing|Policy|Firewall)).*\.md$

  markdown-links:
    name: Validate Markdown Links
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      # Validate Markdown Links
      - name: Check Links in Markdown Files
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
        with:
          config-file: '.github/linters/.markdown-link-check.json'
          check-modified-files-only: 'yes'
          use-verbose-mode: 'yes'
          use-quiet-mode: 'yes'
          base-branch: main

  psrule-tests-modules:
    runs-on: ubuntu-latest
    name: Run PSRule Tests [Modules]
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: PSRule >> Modules
        continue-on-error: true # This is to ensure that the workflow does not stop the next step while the modules are cleaned up
        uses: ./.github/actions/ps-rule
        with:
          option: 'ps-rule.yaml'
          bicepPath: 'src/modules'
          path: ${{ env.PSRULE_DIRECTORY }}

  psrule-tests-configuration:
    runs-on: ubuntu-latest
    name: Run PSRule Tests [Configuration]
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: PSRule >> Configuration
        continue-on-error: true # Larger bicepparam files fail to expand correctly in PSRule
        uses: ./.github/actions/ps-rule
        with:
          option: 'ps-rule.yaml'
          bicepPath: 'src/configuration'
          path: ${{ env.PSRULE_DIRECTORY }}

  pester:
    runs-on: ubuntu-latest
    name: Run Pester Tests
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Run ./scripts/Test-AzPester.ps1
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Write-Information "==> Installing needed modules..." -InformationAction Continue
            Install-Module -Name Pester -Force
            Import-Module Pester
            Write-Information "==> Running script..." -InformationAction Continue
            ./scripts/Test-AzPester.ps1
          azPSVersion: 'latest'

  PS-Docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Checkout Repo
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Checkout PR
      - name: Checkout Pull Request
        run: |
          echo "==> Check out Pull Request"
          gh pr checkout ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email action@github.com

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10' # Version supported for diagrams and graphviz

      - name: Install Diagrams as Code
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
          pip install diagrams

      # Run Get-AzurePricingforSolution.ps1
      - name: Run ./scripts/Get-AzurePricingforSolution.ps1
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Write-Information "==> Running script..." -InformationAction Continue
            ./scripts/Get-AzurePricingforSolution.ps1 -location ${{env.location}} -currencyCode ${{env.currencyCode}}
          azPSVersion: 'latest'

      # Run Set-Documentation.ps1
      - name: Run ./scripts/Set-Documentation.ps1
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Write-Information "==> Installing needed modules..." -InformationAction Continue
            Install-Module -Name powershell-yaml -Force -SkipPublisherCheck
            Install-Module -Name PSDocs -Force -SkipPublisherCheck
            Install-Module -Name PSDocs.Azure -Force -SkipPublisherCheck
            Write-Information "==> Running script..." -InformationAction Continue
            ./scripts/Set-Documentation.ps1 -GitHub
          azPSVersion: 'latest'

      # Run Set-DocumentationforPolicy.ps1
      - name: Run ./scripts/Set-DocumentationforPolicy.ps1
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Write-Information "==> Installing needed modules..." -InformationAction Continue
            Install-Module -Name PSDocs -Force -SkipPublisherCheck
            Write-Information "==> Running script..." -InformationAction Continue
            ./scripts/Set-DocumentationforPolicy.ps1 -GitHub
          azPSVersion: 'latest'

      # Run Set-DocumenationforFirewall.ps1
      - name: Run ./scripts/Set-DocumentationforFirewall.ps1
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Write-Information "==> Installing needed modules..." -InformationAction Continue
            Install-Module -Name PSDocs -Force -SkipPublisherCheck
            Write-Information "==> Running script..." -InformationAction Continue
            ./scripts/Set-DocumentationforFirewall.ps1 -GitHub -diagrams
          azPSVersion: 'latest'

      # Check for changes
      - name: Check for changes
        id: git_status
        run: |
          CHECK_GIT_STATUS=($(git status -s))
          git status -s
          echo "changes=${#CHECK_GIT_STATUS[@]}" >> $GITHUB_OUTPUT

      # Git Commit & Push
      - name: Git Commit & Push (${{ github.event.pull_request.head.repo.full_name }})
        if: steps.git_status.outputs.changes > 0
        run: |
          git config core.autocrlf false
          git add --all
          git commit -m 'Generation of documentation - ${{ github.event.number }} (automated)'
          git push

  # This job is used to update the release draft.
  update_release_draft:
    name: Update Release Draft
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v6
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          config-name: actions/release-drafter/config.yaml
          # disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
